import superTeam from '../img/js/GLP1-super-team.jpg';
import goItMarkup6 from '../img/js/goit-markup-hw-06.jpg';
import foodSta from '../img/js/SLP_FoodSta.jpg';
import hydra from '../img/js/SLP-Hydra.jpg';
import tea from '../img/js/SPL_tea.jpg';

import goItJs07 from '../img/js/goit-js-hw-07.jpg';
import goItJs08 from '../img/js/goit-js-hw-08.jpg';
import goItJs09 from '../img/js/goit-js-hw-09.jpg';
import goItJs10 from '../img/js/goit-js-hw-10.jpg';
import goItJs11 from '../img/js/goit-js-hw-11.jpg';
import goItJs12 from '../img/js/goit-js-hw-12.jpg';
import goItJs12v2 from '../img/js/goit-js-hw-12v2.jpg';
import registrationForm from '../img/js/registration-form.jpg';
import fadeSliderSwiper from '../img/js/slider-fadeEffect-Vite.jpg';
import sliderSwiper from '../img/js/slider-swiper-Vite.jpg';
import testForm1 from '../img/js/SP_test-form-1.jpg';
import ball from '../img/js/sp-ball.jpg';
import blueCollar from '../img/js/SP-BlueCollar-Vite.jpg';
import cardForm from '../img/js/sp-card-form.jpg';
import searchVideoPixabay from '../img/js/sp-SearchVideoPixabay-vite.jpg';
import timeAndQuestion from '../img/js/sp-TimeQuestion-vite.jpg';
import hmCandler from '../img/js/SPL_HM-Candler.jpg';
import homeOfTheBestFood from '../img/js/SPL_home-of-the-best-food.jpg';
import ticTacToe from '../img/js/tic-tac-toe.jpg';
import mechanicalWatch from '../img/js/time-info.jpg';
import teamPortfolio from '../img/js/team-portfolio-js.jpg';

import colorPaletteReact from '../img/react/color-palette-react.jpg';
import reactTodoList from '../img/react/todoList-react.jpg';
import pokemonsReact from '../img/react/pokemon-react.jpg';
import reactHW2 from '../img/react/goit-react-hw-02.jpg';
import reactHW3 from '../img/react/goit-react-hw-03.jpg';
import reactHW4 from '../img/react/goit-react-hw-04.jpg';

export const projectArr = [
  {
    nameOFProject: 'Home of the best food',
    category: 'html css another',
    status: true,
    imgPreview: homeOfTheBestFood,
    alt: 'My first WebSide "Home of the best food',
    codeLink: 'https://github.com/DenysHV1/SPL_home-of-the-best-food',
    siteLink: 'https://denyshv1.github.io/SPL_home-of-the-best-food/',
    technology1: 'html+css',
    technology2: '',
    id: 1,
  },
  {
    nameOFProject: 'Tea',
    category: 'html css another',
    status: true,
    imgPreview: tea,
    alt: 'Tea',
    codeLink: 'https://github.com/DenysHV1/SPL_tea',
    siteLink: 'https://denyshv1.github.io/SPL_tea/',
    technology1: 'html+css',
    technology2: '',
    id: 2,
  },
  {
    nameOFProject: 'Hydra',
    category: 'html css another',
    status: true,
    imgPreview: hydra,
    alt: 'Hydra',
    codeLink: 'https://github.com/DenysHV1/SLP-Hydra',
    siteLink: 'https://denyshv1.github.io/SLP-Hydra/',
    technology1: 'html+css',
    technology2: '',
    id: 3,
  },
  {
    nameOFProject: 'HM Candler',
    category: 'html css another',
    status: true,
    imgPreview: hmCandler,
    alt: 'HM Candler',
    codeLink: 'https://github.com/DenysHV1/SPL_HM-Candler',
    siteLink: 'https://denyshv1.github.io/SPL_HM-Candler/',
    technology1: 'html+css',
    technology2: '',
    id: 4,
  },
  {
    nameOFProject: 'Food Delivery',
    category: 'html css another',
    status: true,
    imgPreview: foodSta,
    alt: 'Food Delivery',
    codeLink: 'https://github.com/DenysHV1/SLP_FoodSta',
    siteLink: 'https://denyshv1.github.io/SLP_FoodSta/',
    technology1: 'html+css',
    technology2: '',
    id: 5,
  },
  {
    nameOFProject: 'Web Studio',
    category: 'html css main',
    status: true,
    imgPreview: goItMarkup6,
    alt: 'Web Studio',
    codeLink: 'https://github.com/DenysHV1/goit-markup-hw-06',
    siteLink: 'https://denyshv1.github.io/goit-markup-hw-06/',
    technology1: 'html+css',
    technology2: '',
    id: 6,
  },
  {
    nameOFProject: 'Watch Charm',
    category: 'html css main',
    status: true,
    imgPreview: superTeam,
    alt: 'Watch Charm',
    codeLink: 'https://github.com/DenysHV1/GLP1-super-team',
    siteLink: 'https://denyshv1.github.io/GLP1-super-team/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 7,
  },
  {
    nameOFProject: 'Mix Features',
    category: 'JS another',
    status: true,
    imgPreview: goItJs07,
    alt: 'Mix Features',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-07',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-07/',
    technologyText: 'Technology: ',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 8,
  },
  {
    nameOFProject: 'Space Ball',
    category: 'JS another',
    status: true,
    imgPreview: ball,
    alt: 'Space Ball',
    codeLink: 'https://github.com/DenysHV1/sp-ball',
    siteLink: 'https://denyshv1.github.io/sp-ball/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 9,
  },
  {
    nameOFProject: 'Gallery basicLightBox',
    category: 'JS another',
    status: true,
    imgPreview: goItJs08,
    alt: 'Gallery basicLightBox',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-08',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-08/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 10,
  },
  {
    nameOFProject: 'My first form',
    category: 'JS another',
    status: true,
    imgPreview: testForm1,
    alt: 'My first form',
    codeLink: 'https://github.com/DenysHV1/SP_test-form-1',
    siteLink: 'https://denyshv1.github.io/SP_test-form-1/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 11,
  },

  {
    nameOFProject: 'Gallery and Form',
    category: 'JS another',
    status: true,
    imgPreview: goItJs09,
    alt: 'Gallery simpleLightBox and Form',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-09',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-09/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 12,
  },
  {
    nameOFProject: 'Payment Form',
    category: 'JS another',
    status: true,
    imgPreview: cardForm,
    alt: 'Payment Form',
    codeLink: 'https://github.com/DenysHV1/sp-card-form',
    siteLink: 'https://denyshv1.github.io/sp-card-form/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 13,
  },
  {
    nameOFProject: 'Registration Form',
    category: 'JS another',
    status: true,
    imgPreview: registrationForm,
    alt: 'Registration Form',
    codeLink: 'https://github.com/DenysHV1/registration-form',
    siteLink: 'https://denyshv1.github.io/registration-form/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 14,
  },
  {
    nameOFProject: 'Swiper Fade Version 1',
    category: 'JS another',
    status: true,
    imgPreview: fadeSliderSwiper,
    alt: 'Swiper Fade Version 1',
    codeLink: 'https://github.com/DenysHV1/slider-fadeEffect-Vite',
    siteLink: 'https://denyshv1.github.io/slider-fadeEffect-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 15,
  },
  {
    nameOFProject: 'Swiper Version 2',
    category: 'JS another',
    status: true,
    imgPreview: sliderSwiper,
    alt: 'Swiper Version 2',
    codeLink: 'https://github.com/DenysHV1/slider-swiper-Vite',
    siteLink: 'https://denyshv1.github.io/slider-swiper-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 16,
  },
  {
    nameOFProject: 'Timer and Snackbar',
    category: 'JS another',
    status: true,
    imgPreview: goItJs10,
    alt: 'Timer and Snackbar',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-10',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-10/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 17,
  },
  {
    nameOFProject: 'Clocks',
    categoryText: 'Category: ',
    category: 'JS another',
    status: true,
    imgPreview: mechanicalWatch,
    alt: 'Clocks',
    codeLink: 'https://github.com/DenysHV1/time-info',
    siteLink: 'https://denyshv1.github.io/time-info/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 18,
  },
  {
    nameOFProject: 'Timers and Questions',
    category: 'JS another',
    status: true,
    imgPreview: timeAndQuestion,
    alt: 'Timers and Questions',
    codeLink: 'https://github.com/DenysHV1/sp-TimeQuestion-vite',
    siteLink: 'https://denyshv1.github.io/sp-TimeQuestion-vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 19,
  },
  {
    nameOFProject: 'Tic Tac Toe',
    category: 'JS main',
    status: true,
    imgPreview: ticTacToe,
    alt: 'Tic Tac Toe',
    codeLink: 'https://github.com/DenysHV1/tic-tac-toe',
    siteLink: 'https://denyshv1.github.io/tic-tac-toe/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 20,
  },
  {
    nameOFProject: 'Simple search',
    category: 'JS another',
    status: true,
    imgPreview: goItJs11,
    alt: 'Simple search',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-11',
    siteLink: 'https:// denyshv1.github.io/goit-js-hw-11/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 21,
  },
  {
    nameOFProject: 'Simple video search',
    category: 'JS another',
    status: true,
    imgPreview: searchVideoPixabay,
    alt: 'Simple video search',
    codeLink: 'https://github.com/DenysHV1/sp-SearchVideoPixabay-vite',
    siteLink: 'https://denyshv1.github.io/sp-SearchVideoPixabay-vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 22,
  },
  {
    nameOFProject: 'Search with pagination 1',
    categoryText: 'Category: ',
    category: 'JS main',
    status: true,
    imgPreview: goItJs12,
    alt: 'Search with pagination version 1',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-12',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-12/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 23,
  },
  {
    nameOFProject: 'Search with pagination 2',
    category: 'JS main',
    status: true,
    imgPreview: goItJs12v2,
    alt: 'Search with pagination version 2',
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-12v2',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-12v2/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 24,
  },

  {
    nameOFProject: 'Blue Collar',
    category: 'JS main',
    status: true,
    imgPreview: blueCollar,
    alt: 'Blue Collar',
    codeLink: 'https://github.com/DenysHV1/SP-BlueCollar-Vite',
    siteLink: 'https://denyshv1.github.io/SP-BlueCollar-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 25,
  },

  {
    nameOFProject: 'Color palette',
    category: 'React another',
    status: true,
    imgPreview: colorPaletteReact,
    alt: 'Color palette',
    codeLink: 'https://github.com/DenysHV1/color-palette-react',
    siteLink: 'https://denyshv1.github.io/color-palette-react/',
    technology1: 'React',
    technology2: 'css',
    id: 26,
  },
  {
    nameOFProject: 'To do list',
    category: 'React main',
    status: true,
    imgPreview: reactTodoList,
    alt: 'To do list',
    codeLink: 'https://github.com/DenysHV1/todoList-react',
    siteLink: 'https://denyshv1.github.io/todoList-react/',
    technology1: 'React',
    technology2: 'css',
    id: 27,
  },
  {
    nameOFProject: 'Pokemons',
    category: 'React main',
    status: true,
    imgPreview: pokemonsReact,
    alt: 'Pokemons',
    codeLink: 'https://github.com/DenysHV1/pokemons-react',
    siteLink: 'https://denyshv1.github.io/pokemons-react/',
    technology1: 'React',
    technology2: 'css',
    id: 28,
  },
  {
    nameOFProject: 'Group project portfolio',
    category: 'React main',
    status: true,
    imgPreview: teamPortfolio,
    alt: 'team portfolio',
    codeLink: 'https://github.com/DenysHV1/team-portfolio-js',
    siteLink: 'https://denyshv1.github.io/team-portfolio-js/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 29,
  },
  {
    nameOFProject: 'Sip Happens Café',
    category: 'React main',
    status: true,
    imgPreview: reactHW2,
    alt: 'Sip Happens Café',
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-02',
    siteLink: 'https://goit-react-hw-02-bay-nine.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 30,
  },
  {
    nameOFProject: 'Phonebook',
    category: 'React main',
    status: true,
    imgPreview: reactHW3,
    alt: 'Phonebook',
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-03',
    siteLink: 'https://goit-react-hw-03-weld-eight.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 31,
  },
  {
    nameOFProject: 'Gallery from Unsplash API',
    category: 'React main',
    status: true,
    imgPreview: reactHW4,
    alt: 'Gallery from Unsplash API',
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-04',
    siteLink: 'https://goit-react-hw-04-henna-seven.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 32,
  },
];
