import superTeam from '../img/js/GLP1-super-team.jpg';
import goItMarkup6 from '../img/js/goit-markup-hw-06.jpg';
import foodSta from '../img/js/SLP_FoodSta.jpg';
import hydra from '../img/js/SLP-Hydra.jpg';
import tea from '../img/js/SPL_tea.jpg';

import goItJs07 from '../img/js/goit-js-hw-07.jpg';
import goItJs08 from '../img/js/goit-js-hw-08.jpg';
import goItJs09 from '../img/js/goit-js-hw-09.jpg';
import goItJs10 from '../img/js/goit-js-hw-10.jpg';
import goItJs11 from '../img/js/goit-js-hw-11.jpg';
import goItJs12 from '../img/js/goit-js-hw-12.jpg';
import goItJs12v2 from '../img/js/goit-js-hw-12v2.jpg';
import registrationForm from '../img/js/registration-form.jpg';
import fadeSliderSwiper from '../img/js/slider-fadeEffect-Vite.jpg';
import sliderSwiper from '../img/js/slider-swiper-Vite.jpg';
import testForm1 from '../img/js/SP_test-form-1.jpg';
import ball from '../img/js/sp-ball.jpg';
import blueCollar from '../img/js/SP-BlueCollar-Vite.jpg';
import cardForm from '../img/js/sp-card-form.jpg';
import searchVideoPixabay from '../img/js/sp-SearchVideoPixabay-vite.jpg';
import timeAndQuestion from '../img/js/sp-TimeQuestion-vite.jpg';
import hmCandler from '../img/js/SPL_HM-Candler.jpg';
import homeOfTheBestFood from '../img/js/SPL_home-of-the-best-food.jpg';
import ticTacToe from '../img/js/tic-tac-toe.jpg';
import mechanicalWatch from '../img/js/time-info.jpg';
import teamPortfolio from '../img/js/team-portfolio-js.jpg';
import oldPortfolio from '../img/js/old-portfolio.jpg';

import colorPaletteReact from '../img/react/color-palette-react.jpg';
import reactTodoList from '../img/react/todoList-react.jpg';
import pokemonsReact from '../img/react/pokemon-react.jpg';
import reactHW2 from '../img/react/goit-react-hw-02.jpg';
import reactHW3 from '../img/react/goit-react-hw-03.jpg';
import reactHW4 from '../img/react/goit-react-hw-04.jpg';
import reactHW5 from '../img/react/filmMix-hw-react-5.jpg';

export const projectArr = [
  {
    name: 'Home of the best food',
    category: 'websites',
    status: true,
    imgPreview: homeOfTheBestFood,
    codeLink: 'https://github.com/DenysHV1/SPL_home-of-the-best-food',
    siteLink: 'https://denyshv1.github.io/SPL_home-of-the-best-food/',
    technology1: 'html+css',
    technology2: '',
    id: 1,
    libraries: [],
  },
  {
    name: 'Tea',
    category: 'websites',
    status: true,
    imgPreview: tea,
    codeLink: 'https://github.com/DenysHV1/SPL_tea',
    siteLink: 'https://denyshv1.github.io/SPL_tea/',
    technology1: 'html+css',
    technology2: '',
    id: 2,
    libraries: [],
  },
  {
    name: 'Hydra',
    category: 'websites',
    status: true,
    imgPreview: hydra,
    codeLink: 'https://github.com/DenysHV1/SLP-Hydra',
    siteLink: 'https://denyshv1.github.io/SLP-Hydra/',
    technology1: 'html+css',
    technology2: '',
    id: 3,
    libraries: [],
  },
  {
    name: 'HM Candler',
    category: 'websites',
    status: true,
    imgPreview: hmCandler,
    codeLink: 'https://github.com/DenysHV1/SPL_HM-Candler',
    siteLink: 'https://denyshv1.github.io/SPL_HM-Candler/',
    technology1: 'html+css',
    technology2: '',
    id: 4,
    libraries: [],
  },
  {
    name: 'Food Delivery',
    category: 'websites',
    status: true,
    imgPreview: foodSta,
    codeLink: 'https://github.com/DenysHV1/SLP_FoodSta',
    siteLink: 'https://denyshv1.github.io/SLP_FoodSta/',
    technology1: 'html+css',
    technology2: '',
    id: 5,
    libraries: [],
  },
  {
    name: 'Web Studio',
    category: 'websites',
    status: true,
    imgPreview: goItMarkup6,
    codeLink: 'https://github.com/DenysHV1/goit-markup-hw-06',
    siteLink: 'https://denyshv1.github.io/goit-markup-hw-06/',
    technology1: 'html+css',
    technology2: '',
    id: 6,
    libraries: [],
  },
  {
    name: 'Watch Charm',
    category: 'websites',
    status: true,
    imgPreview: superTeam,
    codeLink: 'https://github.com/DenysHV1/GLP1-super-team',
    siteLink: 'https://denyshv1.github.io/GLP1-super-team/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 7,
    libraries: [],
  },
  {
    name: 'Mix Features',
    category: 'components',
    status: true,
    imgPreview: goItJs07,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-07',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-07/',
    technologyText: 'Technology: ',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 8,
    libraries: [],
  },
  {
    name: 'Space Ball',
    category: 'web-games',
    status: true,
    imgPreview: ball,
    codeLink: 'https://github.com/DenysHV1/sp-ball',
    siteLink: 'https://denyshv1.github.io/sp-ball/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 9,
    libraries: [],
  },
  {
    name: 'Gallery basicLightBox',
    category: 'components',
    status: true,
    imgPreview: goItJs08,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-08',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-08/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 10,
    libraries: [
      {
        name: 'basicLightBox',
        link: 'https://www.jsdelivr.com/package/npm/basiclightbox',
      },
    ],
  },
  {
    name: 'My first form',
    category: 'components',
    status: true,
    imgPreview: testForm1,
    codeLink: 'https://github.com/DenysHV1/SP_test-form-1',
    siteLink: 'https://denyshv1.github.io/SP_test-form-1/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 11,
    libraries: [],
  },

  {
    name: 'Gallery and Form',
    category: 'components',
    status: true,
    imgPreview: goItJs09,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-09',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-09/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 12,
    libraries: [
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
    ],
  },
  {
    name: 'Payment Form',
    category: 'components',
    status: true,
    imgPreview: cardForm,
    codeLink: 'https://github.com/DenysHV1/sp-card-form',
    siteLink: 'https://denyshv1.github.io/sp-card-form/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 13,
    libraries: [],
  },
  {
    name: 'Registration Form',
    category: 'components',
    status: true,
    imgPreview: registrationForm,
    codeLink: 'https://github.com/DenysHV1/registration-form',
    siteLink: 'https://denyshv1.github.io/registration-form/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 14,
    libraries: [],
  },
  {
    name: 'Swiper Fade Version 1',
    category: 'components',
    status: true,
    imgPreview: fadeSliderSwiper,
    codeLink: 'https://github.com/DenysHV1/slider-fadeEffect-Vite',
    siteLink: 'https://denyshv1.github.io/slider-fadeEffect-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 15,
    libraries: [{ name: 'swiper', link: 'https://swiperjs.com/get-started' }],
  },
  {
    name: 'Swiper Version 2',
    category: 'components',
    status: true,
    imgPreview: sliderSwiper,
    codeLink: 'https://github.com/DenysHV1/slider-swiper-Vite',
    siteLink: 'https://denyshv1.github.io/slider-swiper-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 16,
    libraries: [{ name: 'swiper', link: 'https://swiperjs.com/get-started' }],
  },
  {
    name: 'Timer and Snackbar',
    category: 'components',
    status: true,
    imgPreview: goItJs10,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-10',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-10/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 17,
    libraries: [
      { name: 'flatpickr', link: 'https://www.npmjs.com/package/flatpickr' },
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
    ],
  },
  {
    name: 'Clocks',
    categoryText: 'Category: ',
    category: 'components',
    status: true,
    imgPreview: mechanicalWatch,
    codeLink: 'https://github.com/DenysHV1/time-info',
    siteLink: 'https://denyshv1.github.io/time-info/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 18,
    libraries: [],
  },
  {
    name: 'Timers and Questions',
    category: 'components',
    status: true,
    imgPreview: timeAndQuestion,
    codeLink: 'https://github.com/DenysHV1/sp-TimeQuestion-vite',
    siteLink: 'https://denyshv1.github.io/sp-TimeQuestion-vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 19,
    libraries: [],
  },
  {
    name: 'Tic Tac Toe',
    category: 'web-games',
    status: true,
    imgPreview: ticTacToe,
    codeLink: 'https://github.com/DenysHV1/tic-tac-toe',
    siteLink: 'https://denyshv1.github.io/tic-tac-toe/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 20,
    libraries: [],
  },
  {
    name: 'Simple search',
    category: 'api-visuals',
    status: true,
    imgPreview: goItJs11,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-11',
    siteLink: 'https:// denyshv1.github.io/goit-js-hw-11/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 21,
    libraries: [
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
    ],
  },
  {
    name: 'Simple video search',
    category: 'api-visuals',
    status: true,
    imgPreview: searchVideoPixabay,
    codeLink: 'https://github.com/DenysHV1/sp-SearchVideoPixabay-vite',
    siteLink: 'https://denyshv1.github.io/sp-SearchVideoPixabay-vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 22,
    libraries: [
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
    ],
  },
  {
    name: 'Search with pagination 1',
    category: 'api-visuals',
    status: true,
    imgPreview: goItJs12,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-12',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-12/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 23,
    libraries: [
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
      { name: 'axios', link: 'https://axios-http.com/' },
    ],
  },
  {
    name: 'Search with pagination 2',
    category: 'api-visuals',
    status: true,
    imgPreview: goItJs12v2,
    codeLink: 'https://github.com/DenysHV1/goit-js-hw-12v2',
    siteLink: 'https://denyshv1.github.io/goit-js-hw-12v2/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 24,
    libraries: [
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
      { name: 'axios', link: 'https://axios-http.com/' },
    ],
  },

  {
    name: 'Blue Collar',
    category: 'websites',
    status: true,
    imgPreview: blueCollar,
    codeLink: 'https://github.com/DenysHV1/SP-BlueCollar-Vite',
    siteLink: 'https://denyshv1.github.io/SP-BlueCollar-Vite/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 25,
    libraries: [
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
    ],
  },
  {
    name: 'Old Portfolio',
    category: 'websites',
    status: true,
    imgPreview: oldPortfolio,
    codeLink: 'https://github.com/DenysHV1/old-portfolio',
    siteLink: 'https://denyshv1.github.io/old-portfolio/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 26,
    libraries: [
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
    ],
  },

  {
    name: 'Color palette',
    category: 'components',
    status: true,
    imgPreview: colorPaletteReact,
    codeLink: 'https://github.com/DenysHV1/color-palette-react',
    siteLink: 'https://denyshv1.github.io/color-palette-react/',
    technology1: 'React',
    technology2: 'css',
    id: 27,
    libraries: [],
  },
  {
    name: 'To do list',
    category: 'web-apps',
    status: true,
    imgPreview: reactTodoList,
    codeLink: 'https://github.com/DenysHV1/todoList-react',
    siteLink: 'https://denyshv1.github.io/todoList-react/',
    technology1: 'React',
    technology2: 'css',
    id: 28,
    libraries: [],
  },
  {
    name: 'Pokemons',
    category: 'web-games',
    status: true,
    imgPreview: pokemonsReact,
    codeLink: 'https://github.com/DenysHV1/pokemons-react',
    siteLink: 'https://denyshv1.github.io/pokemons-react/',
    technology1: 'React',
    technology2: 'css',
    id: 29,
    libraries: [],
  },
  {
    name: 'Group project portfolio',
    category: 'websites',
    status: true,
    imgPreview: teamPortfolio,
    codeLink: 'https://github.com/DenysHV1/team-portfolio-js',
    siteLink: 'https://denyshv1.github.io/team-portfolio-js/',
    technology1: 'html+css',
    technology2: 'JavaScript',
    id: 30,
    libraries: [
      { name: 'izitoast', link: 'https://www.npmjs.com/package/izitoast' },
      {
        name: 'simplelightbox',
        link: 'https://www.npmjs.com/package/simplelightbox',
      },
      { name: 'swiper', link: 'https://swiperjs.com/get-started' },
      { name: 'axios', link: 'https://axios-http.com/' },
    ],
  },
  {
    name: 'Sip Happens Café',
    category: 'components',
    status: true,
    imgPreview: reactHW2,
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-02',
    siteLink: 'https://goit-react-hw-02-bay-nine.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 31,
    libraries: [],
  },
  {
    name: 'Phonebook',
    category: 'web-apps',
    status: true,
    imgPreview: reactHW3,
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-03',
    siteLink: 'https://goit-react-hw-03-weld-eight.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 32,
    libraries: [
      { name: 'formik', link: 'https://formik.org/' },
      { name: 'yup', link: 'https://github.com/jquense/yup' },
      { name: 'nanoid', link: 'https://www.npmjs.com/package/nanoid' },
    ],
  },
  {
    name: 'Gallery from Unsplash API',
    category: 'api-visuals',
    status: true,
    imgPreview: reactHW4,
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-04',
    siteLink: 'https://goit-react-hw-04-henna-seven.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 33,
    libraries: [
      {
        name: 'react-loader-spinner',
        link: 'https://github.com/mhnpd/react-loader-spinner',
      },
      {
        name: 'react-modal',
        link: 'https://github.com/reactjs/react-modal?tab=readme-ov-file#examples',
      },
      { name: 'axios', link: 'https://axios-http.com/' },
      { name: 'React Hot Toast', link: 'https://react-hot-toast.com/' },
    ],
  },
  {
    name: 'Film mix info',
    category: 'api-visuals',
    status: true,
    imgPreview: reactHW5,
    codeLink: 'https://github.com/DenysHV1/goit-react-hw-05',
    siteLink: 'https://goit-react-hw-05-sooty-rho.vercel.app/',
    technology1: 'React',
    technology2: 'css',
    id: 34,
    libraries: [
      {
        name: 'react-loader-spinner',
        link: 'https://github.com/mhnpd/react-loader-spinner',
      },
      {
        name: 'react-router',
        link: 'https://reactrouter.com/en/main',
      },
      { name: 'axios', link: 'https://axios-http.com/' },
      { name: 'React Hot Toast', link: 'https://react-hot-toast.com/' },
    ],
  },
];
